[package]
name = "whiteread"
version = "0.1.0"
authors = ["Michał Krasnoborski <mkrdln@gmail.com>"]

description = """\
	Crate for easily reading whitespace-separated values from strings or input. \
	It was made to mimic `cin >>` functionality \
	and to be usable for parsing text input in format commonly used in algorithmic contests."""

documentation = "http://krdln.github.io/whiteread/whiteread/index.html"
homepage = "https://github.com/krdln/whiteread"
repository = "https://github.com/krdln/whiteread"
readme = "README.md"
keywords = ["read", "scan", "parse", "input", "scanf", "cin", "whitespace"]
license = "MIT"
